"""Tests for eclipse geometry and beta angle.

Two tiers run here, and .agent/test.md is emphatic that they are not interchangeable.

**Tier 1 -- analytic.** Closed-form identities that hold for any orbit: the beta angle written in
terms of the published inclination and right ascension of the ascending node, and the textbook
circular-orbit eclipse fraction. These catch unit errors, sign errors, and swapped axes, and they
run offline on every commit. They are *not* an accuracy claim -- their tolerances are wide enough
to absorb the mean-element and frame approximations the closed forms make.

**Tier 3 -- differential against Orekit.** The headline truth source. It compares beta angles and
umbra/penumbra boundary times against `tests/reference/eclipse.json`, generated by
`tools/reference/generate_eclipse.py`. Those tests **skip when the reference is absent**, in the
same way `test_frames.py` does, so a checkout that has never run the generator still gets a green
tier-1 suite rather than a wall of failures.

Everything runs against a frozen element set and astropy's built-in solar ephemeris, so no test
here touches the network.
"""

from __future__ import annotations

import json
import math
import time
from datetime import UTC, datetime, timedelta
from itertools import pairwise
from pathlib import Path
from typing import Any

import numpy as np
import pytest
from astropy import units as u
from astropy.constants import GM_earth
from astropy.coordinates import get_sun
from astropy.time import Time

from science import catalog, eclipse, orbit
from science.provenance import Tier

REFERENCE_PATH = Path(__file__).parent / "reference" / "eclipse.json"

# ISS (ZARYA), frozen so results are reproducible. The same element set the reference generators
# use, so a tier-1 and a tier-3 failure describe the same orbit.
FIXTURE_TLE = catalog.TLE(
    name="ISS (ZARYA)",
    line1="1 25544U 98067A   24001.50000000  .00016717  00000-0  30150-3 0  9004",
    line2="2 25544  51.6416 247.4627 0006703 130.5360 325.0288 15.49815310 10000",
    norad_id=25544,
    source="test-fixture",
    fetched_at_unix=time.time(),
)

# Read straight out of the TLE text rather than from anything the module under test computes, so
# the closed-form checks below stay independent of it. Columns are fixed by the TLE format.
INCLINATION_DEG = float(FIXTURE_TLE.line2[8:16])
RAAN_DEG = float(FIXTURE_TLE.line2[17:25])
MEAN_MOTION_REV_PER_DAY = float(FIXTURE_TLE.line2[52:63])

ORBITAL_PERIOD_S = 86400.0 / MEAN_MOTION_REV_PER_DAY

# Earth's axial tilt. The Sun's declination is bounded by it, which is what bounds the beta angle.
OBLIQUITY_DEG = 23.44

# Earth's equatorial radius, stated here rather than read from the module so the closed-form
# check below does not depend on the value it is checking. IERS 2010, in km.
EARTH_RADIUS_KM = 6378.1366

# Semi-major axis from Kepler's third law and the published mean motion. This is a mean element,
# so it sits about 10 km away from the instantaneous radius; the closed-form tolerances below
# allow for that.
SEMI_MAJOR_AXIS_KM = (
    GM_earth.to_value(u.km**3 / u.s**2) * (ORBITAL_PERIOD_S / (2.0 * math.pi)) ** 2
) ** (1.0 / 3.0)

# ---------------------------------------------------------------------------------------------
# Tolerances, each measured before being set.
# ---------------------------------------------------------------------------------------------

# Closed-form beta angle vs the module, at the element set's own epoch: measured 0.276 deg.
# The residual is dominated by a real modelling difference, not by an error -- a TLE's mean
# elements are referenced to the true equator and equinox of date (TEME), while the module works
# in GCRS, and precession has separated the two by roughly 0.34 deg by 2024. One degree leaves
# 3.6x headroom over that while sitting an order of magnitude below any defect this can catch: a
# sign error on the declination term, a degrees/radians slip, or inclination and node swapped all
# move beta by tens of degrees.
CLOSED_FORM_BETA_TOLERANCE_DEG = 1.0

# Closed-form circular-orbit eclipse fraction vs the module: measured 0.59% relative. The closed
# form assumes a circular orbit and a cylindrical shadow, both of which the module deliberately
# does not; 2% leaves 3.4x headroom. This is a gross-error check, not an accuracy claim -- the
# differential test below is what measures accuracy.
CLOSED_FORM_FRACTION_TOLERANCE = 0.02

# Beta angle vs Orekit. Budgeted from the one known modelling difference between the two:
# astropy's get_sun returns the Sun's *apparent* position and Orekit's returns its *geometric*
# position, which differ by about 21 arcsec of annual aberration -- measured as 0.0047 deg of
# beta. 0.02 deg leaves 4x headroom over that, and sits 17x below the ~0.34 deg signature of a
# TEME/GCRF frame mix-up, which is the defect this exists to catch.
BETA_TOLERANCE_DEG = 0.02

# Sun direction vs Orekit, reported separately so a beta failure can be attributed. The measured
# apparent-vs-geometric separation is 20.8 arcsec; 30 arcsec accommodates it without hiding a
# real ephemeris or frame problem, which would be arcminutes or worse.
SUN_DIRECTION_TOLERANCE_ARCSEC = 30.0

# Eclipse boundary times vs Orekit. Measured contributions:
#     apparent-vs-geometric Sun     0.11 s      (the only known modelling difference)
#     sgp4-vs-Orekit propagation    < 0.001 s   (see test_propagation.py: sub-millimetre)
# Defects this must still catch, measured on this orbit by perturbing the model:
#     mean Earth radius instead of equatorial (6371 km)   3.8 s per boundary
#     penumbra merged into umbra (cylindrical shadow)    11.6 s per boundary
# Two seconds sits 18x above the known difference and safely below both defects.
BOUNDARY_TOLERANCE_S = 2.0


@pytest.fixture(scope="module")
def epoch() -> datetime:
    """The fixture element set's own epoch, in UTC."""
    return orbit.tle_epoch(FIXTURE_TLE)


@pytest.fixture(scope="module")
def one_day(epoch: datetime) -> list[eclipse.Eclipse]:
    """Every complete eclipse in the day following the epoch.

    Module-scoped because each search propagates the orbit a few hundred times; recomputing it
    per test would dominate the suite's runtime for no added coverage.
    """
    return eclipse.eclipse_intervals(FIXTURE_TLE, epoch, days=1.0)


def _reference() -> dict[str, Any]:
    """Load the committed Orekit eclipse reference."""
    return json.loads(REFERENCE_PATH.read_text(encoding="utf-8"))


def _reference_or_skip() -> dict[str, Any]:
    """Return the reference document, or skip the calling test if it has not been generated."""
    if not REFERENCE_PATH.exists():
        pytest.skip("eclipse.json not generated; run tools/reference/generate_eclipse.py")
    return _reference()


def _reference_section(key: str) -> list[dict[str, Any]]:
    """Return one list from the reference, or an empty list, for parametrizing tests."""
    if not REFERENCE_PATH.exists():
        return []
    return _reference()[key]


def _parse_utc(stamp: str) -> datetime:
    """Parse an Orekit ISO-8601 timestamp as a timezone-aware UTC datetime.

    Orekit writes UTC without an offset marker, so attaching the zone here is what stops the
    comparison from silently mixing a naive datetime with an aware one.

    Args:
        stamp: Timestamp as the generator wrote it.

    Returns:
        The same instant, tagged UTC.
    """
    return datetime.fromisoformat(stamp.rstrip("Z")).replace(tzinfo=UTC)


# ---------------------------------------------------------------------------------------------
# Tier 1 -- beta angle
# ---------------------------------------------------------------------------------------------


def test_beta_angle_is_bounded_by_inclination_plus_obliquity(epoch: datetime) -> None:
    """|beta| can never exceed the orbit inclination plus Earth's axial tilt.

    The Sun stays within 23.44 deg of the equator, and the orbit normal is inclined by exactly
    the orbit inclination, so their angular separation -- and therefore beta -- is bounded. This
    is a hard geometric limit no orbit can violate, which makes it the cheapest possible catch
    for a swapped axis, a normal computed as ``v x r`` instead of ``r x v``, or a Sun vector left
    in the wrong frame. All of those produce values well outside the bound.
    """
    limit = INCLINATION_DEG + OBLIQUITY_DEG + 0.5

    for offset_days in range(0, 30, 3):
        beta = eclipse.beta_angle(FIXTURE_TLE, epoch + timedelta(days=offset_days))
        assert beta.unit == "deg"
        assert abs(beta.value) <= limit, (
            f"beta {beta.value:.3f} deg at epoch+{offset_days} d exceeds the geometric limit "
            f"{limit:.3f} deg for a {INCLINATION_DEG} deg orbit"
        )


def test_beta_angle_matches_the_closed_form_at_epoch(epoch: datetime) -> None:
    """The module agrees with the textbook beta identity at the element set's own epoch.

    ``sin(beta) = cos(dec) sin(i) sin(raan - ra) + sin(dec) cos(i)`` expresses beta purely in
    terms of the published orbital elements and the Sun's right ascension and declination. The
    inclination and node are read straight from the TLE text rather than from anything the module
    computed, so this is a genuinely separate route to the same number.

    Only the epoch is checked: the identity uses the *published* node, and a low orbit's node
    regresses several degrees a day, so the closed form goes stale almost immediately. That is a
    property of the shortcut, not of the module.
    """
    beta = eclipse.beta_angle(FIXTURE_TLE, epoch).value

    sun = get_sun(Time(epoch))
    inclination = math.radians(INCLINATION_DEG)
    node = math.radians(RAAN_DEG)

    closed_form = math.degrees(
        math.asin(
            math.cos(sun.dec.rad) * math.sin(inclination) * math.sin(node - sun.ra.rad)
            + math.sin(sun.dec.rad) * math.cos(inclination)
        )
    )

    assert abs(beta - closed_form) <= CLOSED_FORM_BETA_TOLERANCE_DEG, (
        f"beta {beta:.5f} deg disagrees with the closed form {closed_form:.5f} deg by "
        f"{abs(beta - closed_form):.5f} deg (tolerance {CLOSED_FORM_BETA_TOLERANCE_DEG} deg)"
    )


def test_beta_angle_tier_weakens_away_from_epoch(epoch: datetime) -> None:
    """Beta is derived at the element set's epoch and predicted anywhere else.

    Propagating is modelling, and a modelled value must not render like a measured one. Without
    this the trust taxonomy is decoration.
    """
    assert eclipse.beta_angle(FIXTURE_TLE, epoch).tier is Tier.DERIVED
    assert eclipse.beta_angle(FIXTURE_TLE, epoch + timedelta(days=1)).tier is Tier.PREDICTED


def test_beta_angle_receipt_states_frame_time_scale_and_uncertainty(epoch: datetime) -> None:
    """A beta angle carries everything needed to audit it."""
    receipt = eclipse.beta_angle(FIXTURE_TLE, epoch).receipt

    assert receipt.time_scale == "UTC"
    assert "GCRS" in receipt.frame, "beta angle is frame-dependent and must say which frame"
    assert receipt.dataset["sun_ephemeris"], "the solar ephemeris is an input and must be recorded"
    assert receipt.uncertainty["boundary_timing_error_s"] > 0


def test_naive_datetimes_are_rejected(epoch: datetime) -> None:
    """A datetime without a time zone has no time scale, so it is refused rather than assumed."""
    with pytest.raises(ValueError, match="timezone-aware"):
        eclipse.beta_angle(FIXTURE_TLE, epoch.replace(tzinfo=None))

    with pytest.raises(ValueError, match="timezone-aware"):
        eclipse.eclipse_intervals(FIXTURE_TLE, epoch.replace(tzinfo=None), days=1.0)


@pytest.mark.parametrize("days", [0.0, -1.0, 40.0])
def test_out_of_range_spans_are_rejected(epoch: datetime, days: float) -> None:
    """Empty, negative, and unboundedly long spans are refused rather than silently accepted."""
    with pytest.raises(ValueError, match="days must be"):
        eclipse.eclipse_intervals(FIXTURE_TLE, epoch, days=days)


# ---------------------------------------------------------------------------------------------
# Tier 1 -- eclipse geometry
# ---------------------------------------------------------------------------------------------


def test_eclipse_fraction_matches_the_circular_orbit_closed_form(
    epoch: datetime, one_day: list[eclipse.Eclipse]
) -> None:
    """The share of each orbit spent in shadow matches the textbook expression.

    ``f = (1/pi) arccos( sqrt(a^2 - Re^2) / (a cos beta) )`` is the standard circular-orbit,
    cylindrical-shadow eclipse fraction. It is the single strongest offline check available here
    because it ties the two halves of this module together: an error in the beta angle and an
    error in the shadow geometry would both have to conspire to keep this passing.

    The closed form assumes a circular orbit and ignores the Sun's angular size, so it is
    expected to sit a fraction of a percent away -- see the tolerance commentary above.
    """
    beta_rad = math.radians(eclipse.beta_angle(FIXTURE_TLE, epoch).value)
    expected = (
        math.acos(
            math.sqrt(SEMI_MAJOR_AXIS_KM**2 - EARTH_RADIUS_KM**2)
            / (SEMI_MAJOR_AXIS_KM * math.cos(beta_rad))
        )
        / math.pi
    )

    measured = one_day[0].orbit_fraction
    relative = abs(measured - expected) / expected

    assert relative <= CLOSED_FORM_FRACTION_TOLERANCE, (
        f"eclipse fraction {measured:.6f} disagrees with the closed form {expected:.6f} by "
        f"{relative:.3%} (tolerance {CLOSED_FORM_FRACTION_TOLERANCE:.0%})"
    )


def test_eclipses_are_internally_consistent(one_day: list[eclipse.Eclipse]) -> None:
    """Every eclipse enters, darkens, brightens, and exits, in that order.

    The umbra must be strictly nested inside the penumbra: entering total shadow before losing
    part of the Sun is geometrically impossible, and would mean the two boundary searches were
    paired the wrong way round.
    """
    assert one_day, "the ISS should be eclipsed on every revolution at this beta angle"

    for item in one_day:
        assert item.entry_utc < item.exit_utc
        assert item.duration_s > 0
        assert item.umbra_entry_utc is not None, "this orbit is nowhere near a grazing geometry"
        assert item.entry_utc < item.umbra_entry_utc < item.umbra_exit_utc < item.exit_utc
        assert item.umbra_duration_s < item.duration_s
        # Each field is rounded to a millisecond independently, so allow two of them.
        assert item.penumbra_duration_s == pytest.approx(
            item.duration_s - item.umbra_duration_s, abs=2e-3
        )
        # A shadow passage is a fraction of a revolution, never longer than one.
        assert 0.0 < item.orbit_fraction < 1.0
        assert item.duration_s == pytest.approx(item.orbit_fraction * ORBITAL_PERIOD_S, rel=1e-3)


def test_eclipses_are_chronological_and_disjoint(one_day: list[eclipse.Eclipse]) -> None:
    """Eclipses come back in order and do not overlap.

    Overlapping shadow intervals would mean an entry from one revolution had been paired with an
    exit from the next, which inflates a duration without producing any obviously wrong number.
    """
    for earlier, later in pairwise(one_day):
        assert earlier.exit_utc < later.entry_utc


def test_one_eclipse_occurs_per_revolution(one_day: list[eclipse.Eclipse]) -> None:
    """The eclipse count tracks the number of revolutions in the span.

    At a beta angle well inside the critical value the satellite is eclipsed on every orbit, so
    the count must follow the mean motion. A count far below it means eclipses are being missed
    by the coarse search step; far above it means boundaries are being double-counted.
    """
    assert abs(len(one_day) - MEAN_MOTION_REV_PER_DAY) <= 1.5, (
        f"{len(one_day)} eclipses in a day for an orbit that completes "
        f"{MEAN_MOTION_REV_PER_DAY:.3f} revolutions"
    )


def test_penumbra_is_short_but_never_zero(one_day: list[eclipse.Eclipse]) -> None:
    """Each eclipse has a brief partial phase at both edges.

    This is the check that a *conical* shadow model is actually in use. A cylindrical model --
    the common simplification -- makes the Sun a point source and collapses the penumbra to
    nothing, so a zero here means umbra and penumbra have silently become the same thing and
    every reported eclipse is about twelve seconds short at each end. The width follows from the
    Sun's half-degree angular size, which puts it at tens of seconds for a low orbit.
    """
    for item in one_day:
        assert 5.0 < item.penumbra_duration_s < 120.0, (
            f"penumbra of {item.penumbra_duration_s:.1f} s is not consistent with a conical "
            "shadow at low Earth orbit"
        )


def test_shadow_model_constants_are_in_the_units_the_module_claims() -> None:
    """The Earth and Sun radii are kilometres, not metres.

    A factor of a thousand in either radius would not raise. It would produce an eclipse
    computation that runs cleanly and returns numbers of the wrong length entirely -- an Earth
    the size of a city casts no shadow, and every eclipse would quietly vanish.
    """
    assert 6300.0 < eclipse.EARTH_RADIUS_KM < 6400.0
    assert 690000.0 < eclipse.SUN_RADIUS_KM < 700000.0
    # The Sun is roughly 109 Earth radii across; a wrong pairing of units breaks this ratio.
    assert 100.0 < eclipse.SUN_RADIUS_KM / eclipse.EARTH_RADIUS_KM < 115.0


def test_sun_position_is_about_one_astronomical_unit_away(epoch: datetime) -> None:
    """The solar ephemeris returns kilometres at roughly the right distance.

    Guards the one input to this module that comes from outside skyfield. A metres/kilometres slip
    here would put the Sun a thousand times closer, which changes its apparent size and therefore
    the penumbra, without changing the Sun's *direction* -- so beta would still look perfect.
    """
    distance_km = float(
        np.linalg.norm(eclipse._sun_gcrs_km(orbit.TIMESCALE.from_datetime(epoch))[:, 0])
    )
    assert 1.47e8 < distance_km < 1.53e8, f"Sun at {distance_km:.3e} km is not at 1 AU"


# ---------------------------------------------------------------------------------------------
# Tier 1 -- summary
# ---------------------------------------------------------------------------------------------


def test_summary_reports_the_worst_case_a_battery_must_survive(
    epoch: datetime, one_day: list[eclipse.Eclipse]
) -> None:
    """The summary's extremes are the extremes of the intervals it summarises.

    A battery is sized on the longest eclipse in the span, so a maximum that quietly reported a
    mean instead would undersize the cell by the difference -- here about half a minute of
    discharge on every orbit of the mission.
    """
    summary = eclipse.eclipse_summary(FIXTURE_TLE, epoch, days=1.0)

    assert summary["eclipse_count"].value == len(one_day)
    assert summary["max_eclipse_duration"].value == pytest.approx(
        max(item.duration_s for item in one_day), abs=1e-3
    )
    assert summary["min_eclipse_duration"].value == pytest.approx(
        min(item.duration_s for item in one_day), abs=1e-3
    )
    assert (
        summary["min_eclipse_duration"].value
        <= summary["mean_eclipse_duration"].value
        <= summary["max_eclipse_duration"].value
    )
    assert summary["max_umbra_duration"].value < summary["max_eclipse_duration"].value
    assert summary["max_eclipse_duration"].unit == "s"
    assert summary["max_orbit_fraction"].unit == "none"


def test_summary_values_are_predicted_and_carry_a_receipt(epoch: datetime) -> None:
    """Everything in a span summary is a prediction, because a span leaves the epoch.

    The beta angle at the start of the span is the one exception the taxonomy allows: when the
    span begins at the element set's own epoch it is derived, not predicted, and the summary must
    not launder that distinction away in either direction.
    """
    summary = eclipse.eclipse_summary(FIXTURE_TLE, epoch, days=1.0)

    for key in ("max_eclipse_duration", "min_eclipse_duration", "eclipse_count"):
        assert summary[key].tier is Tier.PREDICTED
        assert summary[key].receipt.frame
        assert summary[key].receipt.time_scale == "UTC"
        assert "conical" in summary[key].receipt.notes.lower()

    assert summary["beta_angle_at_start"].tier is Tier.DERIVED
    assert summary["beta_angle_at_end"].tier is Tier.PREDICTED


def test_a_span_with_no_complete_eclipse_reports_zeroes_rather_than_failing(
    epoch: datetime,
) -> None:
    """An eclipse-free span is a valid answer, and says so in its receipt.

    Full sun is a real operating season, not an error: it is when the power problem disappears and
    the thermal one arrives. Raising here would make the caller unable to distinguish it from a
    failure.
    """
    summary = eclipse.eclipse_summary(FIXTURE_TLE, epoch, days=1.0 / 1440.0)

    assert summary["eclipse_count"].value == 0
    assert summary["max_eclipse_duration"].value == 0.0
    assert summary["min_eclipse_duration"].value == 0.0
    assert "No complete eclipse" in summary["max_eclipse_duration"].receipt.notes


def test_partial_eclipses_at_the_span_boundaries_are_discarded(epoch: datetime) -> None:
    """An eclipse already underway when the span opens is omitted, not reported truncated.

    Starting the search a few minutes into a known eclipse must not produce an interval whose
    entry time is simply the start of the search. That would understate the duration and misstate
    the entry, and nothing downstream could tell.
    """
    known = eclipse.eclipse_intervals(FIXTURE_TLE, epoch, days=0.2)[0]
    midway = known.entry_utc + (known.exit_utc - known.entry_utc) / 2

    later = eclipse.eclipse_intervals(FIXTURE_TLE, midway, days=0.2)

    assert later, "the shortened span should still contain complete eclipses"
    assert all(item.entry_utc > known.exit_utc for item in later)


# ---------------------------------------------------------------------------------------------
# Tier 3 -- differential against Orekit
# ---------------------------------------------------------------------------------------------


@pytest.mark.parametrize(
    "sample", _reference_section("beta_angles"), ids=lambda s: f"+{s['offset_minutes']}min"
)
def test_beta_angle_matches_orekit(sample: dict[str, Any]) -> None:
    """skyfield/astropy and Orekit agree on the orbit-plane-to-Sun angle.

    Beta is the most frame-sensitive quantity this project computes, which is exactly why it is
    worth grading against an independent frame stack. A disagreement of a few hundredths of a
    degree points at the solar ephemeris; a disagreement near a third of a degree is the
    signature of TEME being mistaken for GCRF.
    """
    measured = eclipse.beta_angle(FIXTURE_TLE, _parse_utc(sample["epoch_utc"])).value
    difference = abs(measured - sample["beta_deg"])

    assert difference <= BETA_TOLERANCE_DEG, (
        f"beta disagreement at +{sample['offset_minutes']} min: {difference:.6f} deg "
        f"(tolerance {BETA_TOLERANCE_DEG} deg); skyfield {measured:.6f}, "
        f"orekit {sample['beta_deg']:.6f}"
    )


@pytest.mark.parametrize(
    "sample", _reference_section("beta_angles"), ids=lambda s: f"+{s['offset_minutes']}min"
)
def test_sun_direction_matches_orekit(sample: dict[str, Any]) -> None:
    """The two solar ephemerides point in the same direction, to within aberration.

    Checked separately from beta so a failure can be attributed rather than guessed at: if this
    passes and the beta test fails, the problem is in the orbit or the frame, not the Sun.
    """
    when = orbit.TIMESCALE.from_datetime(_parse_utc(sample["epoch_utc"]))

    measured = eclipse._sun_gcrs_km(when)[:, 0]
    measured = measured / np.linalg.norm(measured)

    expected = np.array(sample["sun_gcrf_m"])
    expected = expected / np.linalg.norm(expected)

    separation_arcsec = math.degrees(
        math.acos(min(1.0, max(-1.0, float(np.dot(measured, expected)))))
    ) * 3600.0

    assert separation_arcsec <= SUN_DIRECTION_TOLERANCE_ARCSEC, (
        f"solar ephemerides disagree by {separation_arcsec:.2f} arcsec at "
        f"+{sample['offset_minutes']} min (tolerance {SUN_DIRECTION_TOLERANCE_ARCSEC} arcsec)"
    )


@pytest.mark.parametrize(
    "expected", _reference_section("eclipses"), ids=lambda e: e["entry_utc"]
)
def test_eclipse_boundaries_match_orekit(expected: dict[str, Any]) -> None:
    """Every umbra and penumbra boundary agrees with Orekit's event detection.

    All four boundaries are checked rather than just the duration, because two errors of the same
    sign cancel in a duration: an eclipse shifted bodily by ten seconds has exactly the right
    length and entirely the wrong times.
    """
    reference = _reference_or_skip()
    span_start = _parse_utc(reference["span"]["start_utc"])

    measured = eclipse.eclipse_intervals(FIXTURE_TLE, span_start, days=reference["span"]["days"])
    entry_utc = _parse_utc(expected["entry_utc"])

    match = min(measured, key=lambda item: abs((item.entry_utc - entry_utc).total_seconds()))

    boundaries = [
        ("entry", match.entry_utc, entry_utc),
        ("exit", match.exit_utc, _parse_utc(expected["exit_utc"])),
        ("umbra entry", match.umbra_entry_utc, _parse_utc(expected["umbra_entry_utc"])),
        ("umbra exit", match.umbra_exit_utc, _parse_utc(expected["umbra_exit_utc"])),
    ]

    for label, mine, theirs in boundaries:
        difference = abs((mine - theirs).total_seconds())
        assert difference <= BOUNDARY_TOLERANCE_S, (
            f"{label} disagreement for the eclipse at {expected['entry_utc']}: "
            f"{difference:.3f} s (tolerance {BOUNDARY_TOLERANCE_S} s); "
            f"skyfield {mine.isoformat()}, orekit {theirs.isoformat()}"
        )

    assert abs(match.duration_s - expected["duration_s"]) <= BOUNDARY_TOLERANCE_S
    assert abs(match.umbra_duration_s - expected["umbra_duration_s"]) <= BOUNDARY_TOLERANCE_S


def test_reference_pins_the_same_shadow_model_the_module_uses() -> None:
    """Guard: the two sides of the differential test model the same physical situation.

    Without this the whole tier-3 family is vacuous in a way that is invisible. If someone changed
    the Earth radius in `science.eclipse` and regenerated nothing, or changed the generator and
    not the module, the boundary comparisons would be measuring a deliberate modelling difference
    and calling it accuracy -- while a genuine 4 km error hid inside the widened residual. This
    is the eclipse family's equivalent of `test_teme_and_gcrf_are_actually_different`.
    """
    model = _reference_or_skip()["model"]

    assert model["earth_radius_m"] == pytest.approx(eclipse.EARTH_RADIUS_KM * 1e3, abs=1e-3)
    assert model["sun_radius_m"] == pytest.approx(eclipse.SUN_RADIUS_KM * 1e3, abs=1e-3)
    assert model["earth_flattening"] == 0.0, (
        "the reference must use a spherical Earth to match the module; an oblate one would make "
        "the comparison measure a modelling choice rather than an implementation"
    )


def test_reference_uses_the_same_element_set_as_these_tests() -> None:
    """Guard: the reference and the fixture describe the same satellite.

    A mismatched TLE would make every boundary comparison fail for a reason that has nothing to
    do with the code, which is a slow and confusing way to discover a stale reference file.
    """
    reference_tle = _reference_or_skip()["tle"]

    assert reference_tle["line1"] == FIXTURE_TLE.line1
    assert reference_tle["line2"] == FIXTURE_TLE.line2


def test_reference_beta_angles_actually_vary() -> None:
    """Guard: the reference records a moving Sun, not a frozen one.

    If the generator evaluated the Sun at a single fixed date, every beta sample would be
    identical and the beta tests would pass while checking nothing about time handling. Beta
    drifts several degrees a day at low Earth orbit as the node regresses, so a span of a day must
    show a clear spread.
    """
    samples = _reference_or_skip()["beta_angles"]
    spread = max(s["beta_deg"] for s in samples) - min(s["beta_deg"] for s in samples)

    assert spread > 1.0, (
        f"reference beta angles span only {spread:.4f} deg over a day; the Sun or the orbit plane "
        "is not being advanced with time"
    )


def test_reference_records_its_provenance() -> None:
    """The eclipse reference states where it came from, in which frame, under which model."""
    provenance = _reference_or_skip()["_provenance"]

    assert provenance["source"] == "orekit"
    assert provenance["frame"] == "GCRF"
    assert "conical" in provenance["shadow_model"]
    assert provenance["orekit_jpype_version"] != "unknown"
